apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: todonodejs
    app.kubernetes.io/part-of: mysql
    name: frontend
  name: frontend
  namespace: mysql
spec:
  host: todo.apps.ocp4-mng.example.com
  path: "/todo"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: frontend-emea
    weight: 100
  wildcardPolicy: None
